// __DREDGE_HEADER_START__
// Dredge generated-client template.
//
// This file is the source of record for the client that `dredge codegen`
// emits. It is fully valid TypeScript and is typechecked by `pnpm build`
// (tsc --noEmit over `src`). Codegen reads this file and replaces the marked
// regions below with per-site content; everything else passes through
// verbatim. The default region bodies are legal placeholders so this file
// stands alone — they are never shipped.
//
// Marker regions (each replaced whole, marker lines included):
//   __DREDGE_HEADER__   the "Generated by dredge" banner
//   __DREDGE_URLS__     default worker/manifest URLs
//   __DREDGE_FILTERS__  the DredgeFilters interface
//   __DREDGE_RESULT__   the DredgeResult interface
// __DREDGE_HEADER_END__

// __DREDGE_URLS_START__
const DEFAULT_WORKER_URL = "/search/dredge-worker.js";
const DEFAULT_MANIFEST_URL = "/search/search-manifest.json";
// __DREDGE_URLS_END__

export interface DredgeRange<T> {
  min?: T;
  max?: T;
}

// __DREDGE_FILTERS_START__
export interface DredgeFilters {
  [facet: string]: unknown;
}
// __DREDGE_FILTERS_END__

// __DREDGE_RESULT_START__
export interface DredgeResult {
  [field: string]: unknown;
  score: number;
}
// __DREDGE_RESULT_END__

export interface DredgeFacetBucket {
  value: string | number | boolean;
  count: number;
}

export interface DredgeSearchRequest {
  query?: string;
  filters?: DredgeFilters;
  limit?: number;
  offset?: number;
  includeFacets?: boolean | Array<keyof DredgeFilters>;
}

export type DredgeTier = "hot" | "full";

export interface DredgeSearchResponse {
  total: number;
  hits: DredgeResult[];
  facets?: Partial<Record<keyof DredgeFilters, DredgeFacetBucket[]>>;
  elapsedMs: number;
  // Which database tier served this response. Provisional ("hot") results may be
  // superseded once the full tier swaps in and later responses read "full".
  tier: DredgeTier;
}

export type DredgeStatus =
  | "idle"
  | "checking_support"
  | "fetching_manifest"
  | "checking_storage"
  | "downloading_db"
  | "decompressing_db"
  | "writing_opfs"
  | "opening_db"
  // Cold visit only: the hot tier is serving searches while the full tier
  // downloads in the background. Searches are accepted here and in "ready".
  | "ready_hot"
  | "ready"
  | "failed";

export type DredgeErrorCode =
  | "UNSUPPORTED_OPFS"
  | "UNSUPPORTED_SYNC_ACCESS"
  | "MANIFEST_FETCH_FAILED"
  | "RUNTIME_VERSION_MISMATCH"
  | "SCHEMA_VERSION_MISMATCH"
  | "DB_DOWNLOAD_FAILED"
  | "DB_DECOMPRESS_FAILED"
  | "DB_SIZE_MISMATCH"
  | "DB_STORAGE_CORRUPT"
  | "QUOTA_EXCEEDED"
  | "SQLITE_OPEN_FAILED"
  | "SQLITE_BUSY_LOCKED"
  | "QUERY_FAILED"
  | "FILTER_INVALID"
  | "QUERY_INVALID"
  | "CLIENT_NOT_READY"
  | "STALE_RESPONSE"
  | "WORKER_ERROR"
  | "WORKER_TERMINATED";

export interface DredgeError {
  code: DredgeErrorCode | string;
  message: string;
  details?: unknown;
}

export type DredgeWorkerRequest =
  | { type: "init"; id: number; manifestUrl: string }
  | { type: "search"; id: number; request: DredgeSearchRequest }
  | { type: "destroy"; id: number };

export type DredgeWorkerResponse =
  | { type: "status"; id?: number; status: DredgeStatus }
  | { type: "ready"; id: number; tier: DredgeTier }
  | { type: "searchResult"; id: number; response: DredgeSearchResponse }
  | { type: "error"; id?: number; error: DredgeError };

export interface DredgeClientOptions {
  workerUrl?: string | URL;
  manifestUrl?: string;
  workerFactory?: (url: string | URL) => Worker;
}

type PendingRequest =
  | { kind: "init"; resolve: () => void; reject: (error: DredgeClientError) => void }
  | { kind: "search"; resolve: (response: DredgeSearchResponse) => void; reject: (error: DredgeClientError) => void };

export class DredgeClientError extends Error {
  readonly code: DredgeErrorCode | string;
  readonly details?: unknown;

  constructor(error: DredgeError) {
    super(error.message);
    this.name = "DredgeClientError";
    this.code = error.code;
    this.details = error.details;
  }
}

export class DredgeSearchClient {
  private readonly workerUrl: string | URL;
  private readonly manifestUrl: string;
  private readonly workerFactory?: (url: string | URL) => Worker;
  private worker: Worker | undefined;
  private status: DredgeStatus = "idle";
  private initPromise: Promise<void> | undefined;
  private nextRequestId = 1;
  private inFlightSearchId: number | undefined = undefined;
  private pendingSearch:
    | {
        id: number;
        request: DredgeSearchRequest;
        resolve: (response: DredgeSearchResponse) => void;
        reject: (error: DredgeClientError) => void;
      }
    | undefined = undefined;
  private readonly pending = new Map<number, PendingRequest>();
  private readonly statusListeners = new Set<(status: DredgeStatus) => void>();

  constructor(options: DredgeClientOptions = {}) {
    this.workerUrl = options.workerUrl ?? DEFAULT_WORKER_URL;
    this.manifestUrl = options.manifestUrl ?? DEFAULT_MANIFEST_URL;
    this.workerFactory = options.workerFactory;
  }

  getStatus(): DredgeStatus {
    return this.status;
  }

  onStatus(listener: (status: DredgeStatus) => void): () => void {
    this.statusListeners.add(listener);
    listener(this.status);
    return () => {
      this.statusListeners.delete(listener);
    };
  }

  async init(): Promise<void> {
    if (this.status === "ready" || this.status === "ready_hot") {
      return;
    }
    if (this.status === "failed") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is in a failed state." });
    }
    if (this.initPromise) {
      return this.initPromise;
    }

    const worker = this.ensureWorker();
    const id = this.allocateRequestId();
    const message: DredgeWorkerRequest = { type: "init", id, manifestUrl: this.manifestUrl };
    this.setStatus("checking_support");
    this.initPromise = new Promise<void>((resolve, reject) => {
      this.pending.set(id, { kind: "init", resolve, reject });
      worker.postMessage(message);
    });

    try {
      await this.initPromise;
    } finally {
      this.initPromise = undefined;
    }
  }

  async search(request: DredgeSearchRequest = {}): Promise<DredgeSearchResponse> {
    await this.init();
    // Searches are accepted on the hot tier ("ready_hot") as well as "ready";
    // each response is tagged with the tier that served it.
    if (this.status !== "ready" && this.status !== "ready_hot") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is not ready." });
    }

    this.ensureWorker();
    const id = this.allocateRequestId();

    return new Promise<DredgeSearchResponse>((resolve, reject) => {
      if (this.inFlightSearchId === undefined) {
        // Nothing in flight: submit immediately.
        this.submitSearch(id, request, resolve, reject);
        return;
      }
      // Busy: retain only the newest pending request. Any prior pending is
      // displaced and rejected; intermediate keystrokes never reach the worker.
      if (this.pendingSearch) {
        this.pendingSearch.reject(this.staleError());
      }
      this.pendingSearch = { id, request, resolve, reject };
    });
  }

  destroy(): void {
    if (this.worker) {
      const message: DredgeWorkerRequest = { type: "destroy", id: this.allocateRequestId() };
      this.worker.postMessage(message);
      this.worker.terminate();
      this.worker = undefined;
    }
    this.rejectAll({ code: "WORKER_TERMINATED", message: "Dredge worker was terminated." });
    this.initPromise = undefined;
    this.setStatus("idle");
  }

  private ensureWorker(): Worker {
    if (this.worker) {
      return this.worker;
    }
    const worker = this.workerFactory ? this.workerFactory(this.workerUrl) : new Worker(this.workerUrl, { type: "module" });
    worker.addEventListener("message", this.handleMessage);
    worker.addEventListener("error", this.handleWorkerError);
    this.worker = worker;
    return worker;
  }

  private allocateRequestId(): number {
    return this.nextRequestId++;
  }

  private readonly handleMessage = (event: MessageEvent<DredgeWorkerResponse>): void => {
    const message = event.data;
    if (message.type === "status") {
      this.setStatus(message.status);
      return;
    }

    if (message.type === "ready") {
      // A cold boot resolves init on the hot tier ("ready_hot"); the full tier
      // swap later arrives as a plain `status: "ready"` message.
      this.setStatus(message.tier === "hot" ? "ready_hot" : "ready");
      const pending = this.pending.get(message.id);
      if (pending?.kind === "init") {
        this.pending.delete(message.id);
        pending.resolve();
      }
      return;
    }

    if (message.type === "error") {
      const error = new DredgeClientError(message.error);
      if (message.id !== undefined) {
        const pending = this.pending.get(message.id);
        if (pending) {
          this.pending.delete(message.id);
          pending.reject(error);
          if (pending.kind === "init") {
            this.fail(message.error);
          } else if (message.id === this.inFlightSearchId) {
            this.inFlightSearchId = undefined;
            this.submitPendingSearch();
          }
          return;
        }
      }
      this.fail(message.error);
      return;
    }

    const pending = this.pending.get(message.id);
    if (pending?.kind !== "search") {
      this.pending.delete(message.id);
      return;
    }
    this.pending.delete(message.id);

    if (message.id === this.inFlightSearchId) {
      this.inFlightSearchId = undefined;
      if (this.pendingSearch) {
        // A newer search arrived while this one was in flight: discard it.
        pending.reject(this.staleError());
      } else {
        pending.resolve(message.response);
      }
      this.submitPendingSearch();
      return;
    }

    // Defensive: a response for a search that is no longer in flight.
    pending.reject(this.staleError());
  };

  private readonly handleWorkerError = (): void => {
    this.fail({ code: "WORKER_ERROR", message: "Dredge worker failed." });
  };

  private submitSearch(
    id: number,
    request: DredgeSearchRequest,
    resolve: (response: DredgeSearchResponse) => void,
    reject: (error: DredgeClientError) => void,
  ): void {
    const worker = this.ensureWorker();
    this.inFlightSearchId = id;
    this.pending.set(id, { kind: "search", resolve, reject });
    const message: DredgeWorkerRequest = { type: "search", id, request };
    worker.postMessage(message);
  }

  private submitPendingSearch(): void {
    const next = this.pendingSearch;
    if (!next) {
      return;
    }
    this.pendingSearch = undefined;
    this.submitSearch(next.id, next.request, next.resolve, next.reject);
  }

  private staleError(): DredgeClientError {
    return new DredgeClientError({ code: "STALE_RESPONSE", message: "A newer Dredge search superseded this request." });
  }

  private rejectAll(error: DredgeError): void {
    const clientError = new DredgeClientError(error);
    for (const pending of this.pending.values()) {
      pending.reject(clientError);
    }
    this.pending.clear();
    if (this.pendingSearch) {
      this.pendingSearch.reject(clientError);
      this.pendingSearch = undefined;
    }
    this.inFlightSearchId = undefined;
  }

  private fail(error: DredgeError): void {
    this.rejectAll(error);
    this.initPromise = undefined;
    this.setStatus("failed");
  }

  private setStatus(status: DredgeStatus): void {
    this.status = status;
    for (const listener of this.statusListeners) {
      listener(status);
    }
  }
}
