from __future__ import annotations

import json
import re
from importlib.resources import files
from pathlib import Path

from .compiler import BuildError, DredgeConfig, FacetConfig

DEFAULT_WORKER_URL = "/search/dredge-worker.js"
DEFAULT_MANIFEST_URL = "/search/search-manifest.json"

# The generated client is a real, typechecked TypeScript file in the runtime
# workspace (runtime/src/client.template.ts), vendored into the package by
# `pnpm run vendor`. Codegen reads it and replaces the marked regions with
# per-site content; everything else passes through verbatim. Keeping the client
# as .ts (not a Python string) means client changes are reviewed as TypeScript
# and are covered by `pnpm build`'s tsc pass.
CLIENT_TEMPLATE_RESOURCE = files(__package__).joinpath("vendor", "client.template.ts")


def write_client(config: DredgeConfig, *, require_output: bool = False) -> Path | None:
    configured_path = config.client.get("out")
    if configured_path is None:
        if require_output:
            raise BuildError(
                "CLIENT_OUTPUT_MISSING",
                "client.out must be configured before running codegen",
            )
        return None

    path = _resolve_client_path(config, configured_path)
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(generate_client_source(config), encoding="utf-8")
    except OSError as error:
        raise BuildError(
            "CLIENT_WRITE_FAILED", f"failed to write generated client {path}: {error}"
        ) from error
    return path


def generate_client_source(config: DredgeConfig) -> str:
    worker_url = json.dumps(config.client.get("worker_url", DEFAULT_WORKER_URL))
    manifest_url = json.dumps(DEFAULT_MANIFEST_URL)
    filters = _filters_interface(config)
    result_fields = _result_interface_fields(config)

    template = _read_client_template()
    source = _substitute_region(template, "HEADER", "// Generated by dredge. Do not edit.")
    source = _substitute_region(
        source,
        "URLS",
        f"const DEFAULT_WORKER_URL = {worker_url};\n"
        f"const DEFAULT_MANIFEST_URL = {manifest_url};",
    )
    source = _substitute_region(
        source,
        "FILTERS",
        f"export interface DredgeFilters {{\n{filters}\n}}",
    )
    source = _substitute_region(
        source,
        "RESULT",
        f"export interface DredgeResult {{\n{result_fields}\n  score: number;\n}}",
    )
    return source


def _read_client_template() -> str:
    try:
        return CLIENT_TEMPLATE_RESOURCE.read_text(encoding="utf-8")
    except OSError as error:
        raise BuildError(
            "CLIENT_TEMPLATE_MISSING",
            "this dredge installation ships no client template; rebuild it with"
            f" `pnpm run vendor` in runtime/ ({error})",
        ) from error


def _substitute_region(source: str, name: str, replacement: str) -> str:
    pattern = re.compile(
        rf"^// __DREDGE_{name}_START__$\n.*?^// __DREDGE_{name}_END__$",
        re.MULTILINE | re.DOTALL,
    )
    new_source, count = pattern.subn(lambda _: replacement, source, count=1)
    if count != 1:
        raise BuildError(
            "CLIENT_TEMPLATE_INVALID",
            f"client template is missing the __DREDGE_{name}__ marker region",
        )
    return new_source


def _filters_interface(config: DredgeConfig) -> str:
    return "\n".join(
        f"  {facet.name}?: {_filter_type(facet)};" for facet in config.facets
    )


def _result_interface_fields(config: DredgeConfig) -> str:
    fields = _unique(("id", *config.result_fields))
    lines: list[str] = []
    for field in fields:
        optional, field_type = _result_field_type(config, field)
        marker = "?" if optional else ""
        lines.append(f"  {field}{marker}: {field_type};")
    return "\n".join(lines)


def _filter_type(facet: FacetConfig) -> str:
    if facet.type in {"string", "string_array"}:
        return "string | string[]"
    if facet.type in {"integer", "number"}:
        return "number | number[] | DredgeRange<number>"
    if facet.type == "boolean":
        return "boolean | boolean[]"
    if facet.type == "date":
        return "string | string[] | DredgeRange<string>"
    raise BuildError(
        "CONFIG_INVALID", f"unsupported facet type for codegen: {facet.type}"
    )


def _result_field_type(config: DredgeConfig, field: str) -> tuple[bool, str]:
    if field == "id":
        return False, "number"
    if field in {"title", "url"}:
        return False, "string"
    if field == "description":
        return True, "string"

    facet = config.field_map[field]
    if facet.type in {"string", "date"}:
        return True, "string"
    if facet.type in {"integer", "number"}:
        return True, "number"
    if facet.type == "boolean":
        return True, "boolean"
    if facet.type == "string_array":
        return True, "string[]"
    raise BuildError("CONFIG_INVALID", f"unsupported result field for codegen: {field}")


def _resolve_client_path(config: DredgeConfig, value: str) -> Path:
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = config.path.parent / path
    return path.resolve()


def _unique(values: tuple[str, ...]) -> tuple[str, ...]:
    seen: set[str] = set()
    unique_values: list[str] = []
    for value in values:
        if value not in seen:
            unique_values.append(value)
            seen.add(value)
    return tuple(unique_values)
