// Generated by dredge. Do not edit.

const DEFAULT_WORKER_URL = "/search/dredge-worker.js";
const DEFAULT_MANIFEST_URL = "/search/search-manifest.json";

export interface DredgeRange<T> {
  min?: T;
  max?: T;
}

export interface DredgeFilters {
  category?: string | string[];
  featured?: boolean | boolean[];
  published?: string | string[] | DredgeRange<string>;
  rating?: number | number[] | DredgeRange<number>;
  tags?: string | string[];
  year?: number | number[] | DredgeRange<number>;
}

export interface DredgeResult {
  id: number;
  title: string;
  url: string;
  description?: string;
  category?: string;
  year?: number;
  image?: string;
  score: number;
}

export interface DredgeFacetBucket {
  value: string | number | boolean;
  count: number;
}

export interface DredgeSearchRequest {
  query?: string;
  filters?: DredgeFilters;
  limit?: number;
  offset?: number;
  includeFacets?: boolean | Array<keyof DredgeFilters>;
}

export interface DredgeSearchResponse {
  total: number;
  hits: DredgeResult[];
  facets?: Partial<Record<keyof DredgeFilters, DredgeFacetBucket[]>>;
  elapsedMs: number;
}

export type DredgeStatus =
  | "idle"
  | "checking_support"
  | "fetching_manifest"
  | "checking_storage"
  | "downloading_db"
  | "decompressing_db"
  | "writing_opfs"
  | "opening_db"
  | "ready"
  | "failed";

export type DredgeErrorCode =
  | "UNSUPPORTED_OPFS"
  | "UNSUPPORTED_SYNC_ACCESS"
  | "MANIFEST_FETCH_FAILED"
  | "RUNTIME_VERSION_MISMATCH"
  | "SCHEMA_VERSION_MISMATCH"
  | "DB_DOWNLOAD_FAILED"
  | "DB_DECOMPRESS_FAILED"
  | "DB_SIZE_MISMATCH"
  | "DB_STORAGE_CORRUPT"
  | "QUOTA_EXCEEDED"
  | "SQLITE_OPEN_FAILED"
  | "SQLITE_BUSY_LOCKED"
  | "QUERY_FAILED"
  | "FILTER_INVALID"
  | "QUERY_INVALID"
  | "CLIENT_NOT_READY"
  | "STALE_RESPONSE"
  | "WORKER_ERROR"
  | "WORKER_TERMINATED";

export interface DredgeError {
  code: DredgeErrorCode | string;
  message: string;
  details?: unknown;
}

export type DredgeWorkerRequest =
  | { type: "init"; id: number; manifestUrl: string }
  | { type: "search"; id: number; request: DredgeSearchRequest }
  | { type: "destroy"; id: number };

export type DredgeWorkerResponse =
  | { type: "status"; id?: number; status: DredgeStatus }
  | { type: "ready"; id: number }
  | { type: "searchResult"; id: number; response: DredgeSearchResponse }
  | { type: "error"; id?: number; error: DredgeError };

export interface DredgeClientOptions {
  workerUrl?: string | URL;
  manifestUrl?: string;
  workerFactory?: (url: string | URL) => Worker;
}

type PendingRequest =
  | { kind: "init"; resolve: () => void; reject: (error: DredgeClientError) => void }
  | { kind: "search"; resolve: (response: DredgeSearchResponse) => void; reject: (error: DredgeClientError) => void };

export class DredgeClientError extends Error {
  readonly code: DredgeErrorCode | string;
  readonly details?: unknown;

  constructor(error: DredgeError) {
    super(error.message);
    this.name = "DredgeClientError";
    this.code = error.code;
    this.details = error.details;
  }
}

export class DredgeSearchClient {
  private readonly workerUrl: string | URL;
  private readonly manifestUrl: string;
  private readonly workerFactory?: (url: string | URL) => Worker;
  private worker: Worker | undefined;
  private status: DredgeStatus = "idle";
  private initPromise: Promise<void> | undefined;
  private nextRequestId = 1;
  private latestSearchRequestId = 0;
  private readonly pending = new Map<number, PendingRequest>();
  private readonly statusListeners = new Set<(status: DredgeStatus) => void>();

  constructor(options: DredgeClientOptions = {}) {
    this.workerUrl = options.workerUrl ?? DEFAULT_WORKER_URL;
    this.manifestUrl = options.manifestUrl ?? DEFAULT_MANIFEST_URL;
    this.workerFactory = options.workerFactory;
  }

  getStatus(): DredgeStatus {
    return this.status;
  }

  onStatus(listener: (status: DredgeStatus) => void): () => void {
    this.statusListeners.add(listener);
    listener(this.status);
    return () => {
      this.statusListeners.delete(listener);
    };
  }

  async init(): Promise<void> {
    if (this.status === "ready") {
      return;
    }
    if (this.status === "failed") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is in a failed state." });
    }
    if (this.initPromise) {
      return this.initPromise;
    }

    const worker = this.ensureWorker();
    const id = this.allocateRequestId();
    const message: DredgeWorkerRequest = { type: "init", id, manifestUrl: this.manifestUrl };
    this.setStatus("checking_support");
    this.initPromise = new Promise<void>((resolve, reject) => {
      this.pending.set(id, { kind: "init", resolve, reject });
      worker.postMessage(message);
    });

    try {
      await this.initPromise;
    } finally {
      this.initPromise = undefined;
    }
  }

  async search(request: DredgeSearchRequest = {}): Promise<DredgeSearchResponse> {
    await this.init();
    if (this.status !== "ready") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is not ready." });
    }

    const worker = this.ensureWorker();
    const id = this.allocateRequestId();
    this.rejectOlderSearches(id);
    this.latestSearchRequestId = id;
    const message: DredgeWorkerRequest = { type: "search", id, request };

    return new Promise<DredgeSearchResponse>((resolve, reject) => {
      this.pending.set(id, { kind: "search", resolve, reject });
      worker.postMessage(message);
    });
  }

  destroy(): void {
    if (this.worker) {
      const message: DredgeWorkerRequest = { type: "destroy", id: this.allocateRequestId() };
      this.worker.postMessage(message);
      this.worker.terminate();
      this.worker = undefined;
    }
    this.rejectAll({ code: "WORKER_TERMINATED", message: "Dredge worker was terminated." });
    this.initPromise = undefined;
    this.latestSearchRequestId = 0;
    this.setStatus("idle");
  }

  private ensureWorker(): Worker {
    if (this.worker) {
      return this.worker;
    }
    const worker = this.workerFactory ? this.workerFactory(this.workerUrl) : new Worker(this.workerUrl, { type: "module" });
    worker.addEventListener("message", this.handleMessage);
    worker.addEventListener("error", this.handleWorkerError);
    this.worker = worker;
    return worker;
  }

  private allocateRequestId(): number {
    return this.nextRequestId++;
  }

  private readonly handleMessage = (event: MessageEvent<DredgeWorkerResponse>): void => {
    const message = event.data;
    if (message.type === "status") {
      this.setStatus(message.status);
      return;
    }

    if (message.type === "ready") {
      this.setStatus("ready");
      const pending = this.pending.get(message.id);
      if (pending?.kind === "init") {
        this.pending.delete(message.id);
        pending.resolve();
      }
      return;
    }

    if (message.type === "error") {
      const error = new DredgeClientError(message.error);
      if (message.id !== undefined) {
        const pending = this.pending.get(message.id);
        if (pending) {
          this.pending.delete(message.id);
          pending.reject(error);
          if (pending.kind === "init") {
            this.fail(message.error);
          }
          return;
        }
      }
      this.fail(message.error);
      return;
    }

    if (message.id < this.latestSearchRequestId) {
      this.pending.delete(message.id);
      return;
    }

    const pending = this.pending.get(message.id);
    if (pending?.kind === "search") {
      this.pending.delete(message.id);
      pending.resolve(message.response);
    }
  };

  private readonly handleWorkerError = (): void => {
    this.fail({ code: "WORKER_ERROR", message: "Dredge worker failed." });
  };

  private rejectOlderSearches(newestRequestId: number): void {
    for (const [id, pending] of this.pending) {
      if (pending.kind === "search" && id < newestRequestId) {
        this.pending.delete(id);
        pending.reject(new DredgeClientError({ code: "STALE_RESPONSE", message: "A newer Dredge search superseded this request." }));
      }
    }
  }

  private rejectAll(error: DredgeError): void {
    const clientError = new DredgeClientError(error);
    for (const pending of this.pending.values()) {
      pending.reject(clientError);
    }
    this.pending.clear();
  }

  private fail(error: DredgeError): void {
    this.rejectAll(error);
    this.initPromise = undefined;
    this.setStatus("failed");
  }

  private setStatus(status: DredgeStatus): void {
    this.status = status;
    for (const listener of this.statusListeners) {
      listener(status);
    }
  }
}
