// Generated by dredge. Do not edit.

const DEFAULT_WORKER_URL = "/search/dredge-worker.js";
const DEFAULT_MANIFEST_URL = "/search/search-manifest.json";

export interface DredgeRange<T> {
  min?: T;
  max?: T;
}

// The document columns this site can order by. Store Fields are carried on a
// hit but not orderable, and the engine rejects them with QUERY_INVALID, so
// they are absent from this union.
export type DredgeSortField =
  | "id"
  | "url"
  | "title"
  | "description"
  | "category"
  | "featured"
  | "published"
  | "rating"
  | "year";

export interface DredgeSort {
  field: DredgeSortField;
  direction?: "asc" | "desc";
}

export interface DredgeFilters {
  category?: string | string[];
  featured?: boolean | boolean[];
  published?: string | string[] | DredgeRange<string>;
  rating?: number | number[] | DredgeRange<number>;
  tags?: string | string[];
  year?: number | number[] | DredgeRange<number>;
}

export interface DredgeMark {
  // Offsets into the field's own string, as returned on the hit.
  start: number;
  length: number;
}

// Marked spans per text field of a hit. Spans, never markup: the consumer
// renders them into its own DOM.
export type DredgeMarks = Record<string, DredgeMark[]>;

export interface DredgeResult {
  id: number;
  title: string;
  url: string;
  description?: string;
  category?: string;
  year?: number;
  image?: string;
  score: number;
  band: number;
  marks?: DredgeMarks;
}

export interface DredgeFacetBucket {
  value: string | number | boolean;
  count: number;
}

export interface DredgeSearchRequest {
  query?: string;
  filters?: DredgeFilters;
  limit?: number;
  offset?: number;
  includeFacets?: boolean | Array<keyof DredgeFilters>;
  // Explicit ordering. When omitted, results are ordered by relevance for
  // keyword queries and by document id for a match-all browse.
  sort?: DredgeSort;
}

export interface DredgeSearchResponse {
  total: number;
  hits: DredgeResult[];
  facets?: Partial<Record<keyof DredgeFilters, DredgeFacetBucket[]>>;
  elapsedMs: number;
}

export type DredgeSuggestKind = "correction" | "completion";

export interface DredgeSuggestRequest {
  // A single term: the word the reader typed for a correction, the partial word
  // they are still typing for a completion. Phrases are not suggested against.
  term: string;
  kind: DredgeSuggestKind;
  limit?: number;
}

export interface DredgeSuggestion {
  // A term the index actually holds, so accepting this suggestion cannot land
  // the reader on zero results.
  term: string;
  documentFrequency: number;
  // Edit distance from what the reader typed; for a completion, the number of
  // characters it adds.
  distance: number;
}

export interface DredgeSuggestResponse {
  suggestions: DredgeSuggestion[];
  elapsedMs: number;
}

export type DredgeStatus =
  | "idle"
  | "checking_support"
  | "fetching_manifest"
  | "checking_storage"
  | "downloading_db"
  | "decompressing_db"
  | "writing_opfs"
  | "opening_db"
  | "ready"
  | "failed";

export type DredgeErrorCode =
  | "UNSUPPORTED_OPFS"
  | "UNSUPPORTED_SYNC_ACCESS"
  | "MANIFEST_FETCH_FAILED"
  | "RUNTIME_VERSION_MISMATCH"
  | "SCHEMA_VERSION_MISMATCH"
  | "DB_DOWNLOAD_FAILED"
  | "DB_DECOMPRESS_FAILED"
  | "DB_SIZE_MISMATCH"
  | "DB_STORAGE_CORRUPT"
  | "QUOTA_EXCEEDED"
  | "SQLITE_OPEN_FAILED"
  | "SQLITE_BUSY_LOCKED"
  | "QUERY_FAILED"
  | "FILTER_INVALID"
  | "QUERY_INVALID"
  | "CLIENT_NOT_READY"
  | "STALE_RESPONSE"
  | "WORKER_ERROR"
  | "WORKER_TERMINATED";

export interface DredgeError {
  code: DredgeErrorCode | string;
  message: string;
  details?: unknown;
}

export type DredgeWorkerRequest =
  | { type: "init"; id: number; manifestUrl: string }
  | { type: "search"; id: number; request: DredgeSearchRequest }
  | { type: "suggest"; id: number; request: DredgeSuggestRequest }
  | { type: "destroy"; id: number };

export type DredgeWorkerResponse =
  | { type: "status"; id?: number; status: DredgeStatus }
  | { type: "ready"; id: number }
  | { type: "searchResult"; id: number; response: DredgeSearchResponse }
  | { type: "suggestResult"; id: number; response: DredgeSuggestResponse }
  | { type: "error"; id?: number; error: DredgeError };

export interface DredgeClientOptions {
  workerUrl?: string | URL;
  manifestUrl?: string;
  workerFactory?: (url: string | URL) => Worker;
}

type PendingRequest =
  | { kind: "init"; resolve: () => void; reject: (error: DredgeClientError) => void }
  | { kind: "search"; resolve: (response: DredgeSearchResponse) => void; reject: (error: DredgeClientError) => void }
  | { kind: "suggest"; resolve: (response: DredgeSuggestResponse) => void; reject: (error: DredgeClientError) => void };

export class DredgeClientError extends Error {
  readonly code: DredgeErrorCode | string;
  readonly details?: unknown;

  constructor(error: DredgeError) {
    super(error.message);
    this.name = "DredgeClientError";
    this.code = error.code;
    this.details = error.details;
  }
}

export class DredgeSearchClient {
  private readonly workerUrl: string | URL;
  private readonly manifestUrl: string;
  private readonly workerFactory?: (url: string | URL) => Worker;
  private worker: Worker | undefined;
  private status: DredgeStatus = "idle";
  private initPromise: Promise<void> | undefined;
  private nextRequestId = 1;
  private inFlightSearchId: number | undefined = undefined;
  private pendingSearch:
    | {
        id: number;
        request: DredgeSearchRequest;
        resolve: (response: DredgeSearchResponse) => void;
        reject: (error: DredgeClientError) => void;
      }
    | undefined = undefined;
  private readonly pending = new Map<number, PendingRequest>();
  private readonly statusListeners = new Set<(status: DredgeStatus) => void>();

  constructor(options: DredgeClientOptions = {}) {
    this.workerUrl = options.workerUrl ?? DEFAULT_WORKER_URL;
    this.manifestUrl = options.manifestUrl ?? DEFAULT_MANIFEST_URL;
    this.workerFactory = options.workerFactory;
  }

  getStatus(): DredgeStatus {
    return this.status;
  }

  onStatus(listener: (status: DredgeStatus) => void): () => void {
    this.statusListeners.add(listener);
    listener(this.status);
    return () => {
      this.statusListeners.delete(listener);
    };
  }

  async init(): Promise<void> {
    if (this.status === "ready") {
      return;
    }
    if (this.status === "failed") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is in a failed state." });
    }
    if (this.initPromise) {
      return this.initPromise;
    }

    const worker = this.ensureWorker();
    const id = this.allocateRequestId();
    const message: DredgeWorkerRequest = { type: "init", id, manifestUrl: this.manifestUrl };
    this.setStatus("checking_support");
    this.initPromise = new Promise<void>((resolve, reject) => {
      this.pending.set(id, { kind: "init", resolve, reject });
      worker.postMessage(message);
    });

    try {
      await this.initPromise;
    } finally {
      this.initPromise = undefined;
    }
  }

  async search(request: DredgeSearchRequest = {}): Promise<DredgeSearchResponse> {
    await this.init();
    if (this.status !== "ready") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is not ready." });
    }

    this.ensureWorker();
    const id = this.allocateRequestId();

    return new Promise<DredgeSearchResponse>((resolve, reject) => {
      if (this.inFlightSearchId === undefined) {
        // Nothing in flight: submit immediately.
        this.submitSearch(id, request, resolve, reject);
        return;
      }
      // Busy: retain only the newest pending request. Any prior pending is
      // displaced and rejected; intermediate keystrokes never reach the worker.
      if (this.pendingSearch) {
        this.pendingSearch.reject(this.staleError());
      }
      this.pendingSearch = { id, request, resolve, reject };
    });
  }

  // Suggestions are not coalesced the way searches are: a correction and a
  // completion answer different questions, and neither supersedes a search.
  async suggest(request: DredgeSuggestRequest): Promise<DredgeSuggestResponse> {
    await this.init();
    if (this.status !== "ready") {
      throw new DredgeClientError({ code: "CLIENT_NOT_READY", message: "Dredge worker is not ready." });
    }

    const worker = this.ensureWorker();
    const id = this.allocateRequestId();

    return new Promise<DredgeSuggestResponse>((resolve, reject) => {
      this.pending.set(id, { kind: "suggest", resolve, reject });
      const message: DredgeWorkerRequest = { type: "suggest", id, request };
      worker.postMessage(message);
    });
  }

  destroy(): void {
    if (this.worker) {
      const message: DredgeWorkerRequest = { type: "destroy", id: this.allocateRequestId() };
      this.worker.postMessage(message);
      this.worker.terminate();
      this.worker = undefined;
    }
    this.rejectAll({ code: "WORKER_TERMINATED", message: "Dredge worker was terminated." });
    this.initPromise = undefined;
    this.setStatus("idle");
  }

  private ensureWorker(): Worker {
    if (this.worker) {
      return this.worker;
    }
    const worker = this.workerFactory ? this.workerFactory(this.workerUrl) : new Worker(this.workerUrl, { type: "module" });
    worker.addEventListener("message", this.handleMessage);
    worker.addEventListener("error", this.handleWorkerError);
    this.worker = worker;
    return worker;
  }

  private allocateRequestId(): number {
    return this.nextRequestId++;
  }

  private readonly handleMessage = (event: MessageEvent<DredgeWorkerResponse>): void => {
    const message = event.data;
    if (message.type === "status") {
      this.setStatus(message.status);
      return;
    }

    if (message.type === "ready") {
      this.setStatus("ready");
      const pending = this.pending.get(message.id);
      if (pending?.kind === "init") {
        this.pending.delete(message.id);
        pending.resolve();
      }
      return;
    }

    if (message.type === "error") {
      const error = new DredgeClientError(message.error);
      if (message.id !== undefined) {
        const pending = this.pending.get(message.id);
        if (pending) {
          this.pending.delete(message.id);
          pending.reject(error);
          if (pending.kind === "init") {
            this.fail(message.error);
          } else if (message.id === this.inFlightSearchId) {
            this.inFlightSearchId = undefined;
            this.submitPendingSearch();
          }
          return;
        }
      }
      this.fail(message.error);
      return;
    }

    if (message.type === "suggestResult") {
      const pending = this.pending.get(message.id);
      this.pending.delete(message.id);
      if (pending?.kind === "suggest") {
        pending.resolve(message.response);
      }
      return;
    }

    const pending = this.pending.get(message.id);
    if (pending?.kind !== "search") {
      this.pending.delete(message.id);
      return;
    }
    this.pending.delete(message.id);

    if (message.id === this.inFlightSearchId) {
      this.inFlightSearchId = undefined;
      if (this.pendingSearch) {
        // A newer search arrived while this one was in flight: discard it.
        pending.reject(this.staleError());
      } else {
        pending.resolve(message.response);
      }
      this.submitPendingSearch();
      return;
    }

    // Defensive: a response for a search that is no longer in flight.
    pending.reject(this.staleError());
  };

  private readonly handleWorkerError = (): void => {
    this.fail({ code: "WORKER_ERROR", message: "Dredge worker failed." });
  };

  private submitSearch(
    id: number,
    request: DredgeSearchRequest,
    resolve: (response: DredgeSearchResponse) => void,
    reject: (error: DredgeClientError) => void,
  ): void {
    const worker = this.ensureWorker();
    this.inFlightSearchId = id;
    this.pending.set(id, { kind: "search", resolve, reject });
    const message: DredgeWorkerRequest = { type: "search", id, request };
    worker.postMessage(message);
  }

  private submitPendingSearch(): void {
    const next = this.pendingSearch;
    if (!next) {
      return;
    }
    this.pendingSearch = undefined;
    this.submitSearch(next.id, next.request, next.resolve, next.reject);
  }

  private staleError(): DredgeClientError {
    return new DredgeClientError({ code: "STALE_RESPONSE", message: "A newer Dredge search superseded this request." });
  }

  private rejectAll(error: DredgeError): void {
    const clientError = new DredgeClientError(error);
    for (const pending of this.pending.values()) {
      pending.reject(clientError);
    }
    this.pending.clear();
    if (this.pendingSearch) {
      this.pendingSearch.reject(clientError);
      this.pendingSearch = undefined;
    }
    this.inFlightSearchId = undefined;
  }

  private fail(error: DredgeError): void {
    this.rejectAll(error);
    this.initPromise = undefined;
    this.setStatus("failed");
  }

  private setStatus(status: DredgeStatus): void {
    this.status = status;
    for (const listener of this.statusListeners) {
      listener(status);
    }
  }
}
